package edu.projecteuler.problem.impl;

import edu.projecteuler.problem.AbstractProblem;
import edu.projecteuler.problem.annotation.Problem;

@Problem
public class Problem2 extends AbstractProblem{

	public String execute() {
		return null;
	}

	public String getTitle() {
		return "Even Fibonacci numbers";
	}

	public String getDescription() {
		return descriptionBuilder.append("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:")
		.append(NEW_LINE)
		.append("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...")
		.append(NEW_LINE)
		.append("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.")
		.toString();
	}

}
